### ISSUE TITLE
用手机拍照的图，然后再解析暗水印会失效，解析成全黑的图

### ISSUE THREAD

**Issue by wloops** [zhensherlock/watermark-js-plus#1028]
### 问题描述

用手机拍照的图，然后再解析暗水印会失效，解析成全黑的图

### 复现步骤

就在文档示例里测试生成的暗水印，然后也在文档提供的解析暗水印处上传就只看到全黑的图片
如图：
![faacb9f9ba9baf782e8461e88a41e28](https://github.com/user-attachments/assets/e554167a-eeba-4746-82c5-59c3c90514a4)
![Clip_2024-11-10_23-20-38](https://github.com/user-attachments/assets/5fe4cf93-6e6a-4cb9-ad27-3c8f608127a6)
### 环境详情

- **`watermark-js-plus` version:**
- **`vue` version:**
- **`react` version:**
- **`react-dom` version:**

**Comment by zhensherlock** [comment]
你好，暂时只支持截图
