### ISSUE TITLE
ie下报错

### ISSUE THREAD

**Issue by yz1311** [zhensherlock/watermark-js-plus#1048]
### 问题描述

ie下直接报错
```
requirejs require error： TypeError: 对象不支持“includes”属性或方法
```

### 环境详情

https://www.unpkg.com/watermark-js-plus@1.5.6/dist/ie/index.iife.min.js

- **`watermark-js-plus` version:**
- **`vue` version:**
- **`react` version:**
- **`react-dom` version:**

**Comment by zhensherlock** [comment]
是ie11吗？

**Comment by yz1311** [comment]
> 是ie11吗？
对，win11下edge浏览器开启的ie兼容模式

**Comment by zhensherlock** [comment]
改成1.5.7的版本试试，文档上我忘记改了

**Comment by yz1311** [comment]
> 改成1.5.7的版本试试，文档上我忘记改了


可以了，谢谢
![00AEA838](https://github.com/user-attachments/assets/f6babe6a-ca9b-4016-938a-e2886df387c9)
