### ISSUE TITLE
旋转水印幕布

### ISSUE THREAD

**Issue by Z-YHDD** [zhensherlock/watermark-js-plus#11]
你好， 我想问一下，如何旋转整个水印幕布至固定的角度，让水印看起来像是错开了一样，
旋转前
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/9f1e8be7-6f2c-4f5c-9f8b-fdc03079f93f)
旋转后
![企业微信截图_16841187015791](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/d70b0b1a-2a37-4cec-b91d-01de13692d56)

**Comment by zhensherlock** [comment]
你好，没有明白你要什么样的效果，如果是水印旋转可以用rotate参数

**Comment by Z-YHDD** [comment]
你好，感谢回复，可能是我没表达清楚，我换一种说法吧，我想要水印可以错开展示，目前的水印没办法像下图一样行与行之间错开展示，
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/f02479d9-057a-4453-831a-172c91448455)

**Comment by zhensherlock** [comment]
抱歉，目前暂时不支持上述所说的展现形式，我们会尽快考虑加入该功能。

**Comment by zhensherlock** [comment]
@Z-YHDD 
初始化添加以下参数
``` js {2-6}
const watermark = new Watermark({
  layout: 'grid',
  gridLayoutOptions: {
    rows: 2,
    cols: 2,
    matrix: [[1,0], [0,1]]
  }
})
```
layout：布局方式
gridLayoutOptions.rows：行数
gridLayoutOptions.cols：列数
gridLayoutOptions.matrix：标记某行某列显示状态，1为显示，0为隐藏
