### ISSUE TITLE
水印销毁问题

### ISSUE THREAD

**Issue by Z-YHDD** [zhensherlock/watermark-js-plus#118]
你好，我想问一下，为何我在一个文件中创建了水印，在另一个文件中引入水印后想要销毁却销毁不掉

我的操作流程是这样的：
第一步：项目启动时创建水印
![企业微信截图_16966484544504](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/f69666c7-1b5d-4e00-9e02-da8d4705dcc8)

第二步：人为触发开启或关闭水印
![企业微信截图_16966485791939](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/5f12cffa-5274-4e1a-a582-c76e0eff211f)

第三步：重新构建水印
![企业微信截图_16966486283510](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/0d8c862a-384e-435d-aa7b-51f6a397b2a8)

目前的问题是：当我在项目启动时就创建水印的话，是无法在第二步进行销毁水印的，但是如果我第一步没有创建水印，而是在第二部进行开启水印后再关闭水印，是可以正常销毁水印的

以下是补充代码：
1.创建水印的方法：可以同时创建明水印和暗水印
![企业微信截图_16966488237364](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/03560ed7-558f-4ebd-8781-68f83a8119bd)

2.销毁水印的方法
![企业微信截图_16966488602485](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/d9e3a718-6602-4ab3-8760-a3dde53ff780)

**Comment by zhensherlock** [comment]
@Z-YHDD watermark-js-plus 是什么版本的

**Comment by Z-YHDD** [comment]
你好，是1.3.7版本的

**Comment by zhensherlock** [comment]
<img width="1078" alt="image" src="https://github.com/zhensherlock/watermark-js-plus/assets/3541162/59a547c8-1e3c-47dc-9fff-70990709ede8">
这个watermark是什么？上面有new吗？

**Comment by Z-YHDD** [comment]
这个watermark是在上面引入的
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/5a4ea38b-efef-4b40-adc4-755a1e2bb07e)

而引入的文件的代码是这样的，我上面提问所给的代码有用到watermark时都是引用的此文件
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/7918d846-1f00-4540-8b9f-e6bf85031b70)

**Comment by zhensherlock** [comment]
注册水印的，有个forEach循环，会不会是这里导致的

**Comment by Z-YHDD** [comment]
我刚刚试了试，应该不是这个forEach循环的问题，我把循环去掉，不管服务端查出什么数据，我都去创建水印，会出现不管我是只创建明水印还是只创建暗水印还是明暗水印一起创建，所创建的水印都无法销毁了，且控制台没有报任何错误
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/553076e1-e8ec-4eab-91ab-e9da5bcef055)

下面是销毁水印的代码
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/b0d0ee28-ecf7-43ad-814f-936fac52ae36)

**Comment by zhensherlock** [comment]
可以先尝试用文档上的用法新建水印，再删除水印吗，看看有没有问题，先不要用你封装的Watermark类文件

**Comment by Z-YHDD** [comment]
你好，我使用文档上的方法进行创建，还是有以下问题。
1.我单独创建明水印可以正常创建，但是无法销毁。
2.我单独创建暗水印可以正常创建，但是无法销毁。
3.当我同时创建明水印和暗水印时，哪个水印后创建，就会使用哪个水印
4.当我同时创建明水印和暗水印时，所创建的水印无法销毁

* 我把水印的版本从1.3.7提升到了1.3.10

* 我使用的文档的创建方法为下图图
![企业微信截图_16968434856708](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/8e3b747d-04af-4e33-be98-544d78a7452a)

* 我的水印导入是这样的
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/df2459af-9371-4269-8f40-3bd9d3d538ef)

* 我所写的创建明暗水印的代码如下图
![image](https://github.com/zhensherlock/watermark-js-plus/assets/100017088/697f384f-d014-43fa-9967-475062c4c51f)

**Comment by zhensherlock** [comment]
create是异步方法，需要使用await，加上await再试试

**Comment by zhensherlock** [comment]
示例：https://codesandbox.io/s/nervous-shockley-yxtjp2?file=/src/App.vue:501-535
