### ISSUE TITLE
无法销毁水印

### ISSUE THREAD

**Issue by QW1kou** [zhensherlock/watermark-js-plus#15]
调用了destroy()方法 但是无法销毁

**Comment by zhensherlock** [comment]
请提供下代码，官网上的示例是可以删除的 https://zhensherlock.github.io/watermark-js-plus/guide/watermark.html

**Comment by QW1kou** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/1aeb2d96-8740-41a2-9a76-b955d9d06715)

**Comment by QW1kou** [comment]
水印只能添加一次吗，我想把水印内容改成动态的可以吗

**Comment by zhensherlock** [comment]
监听store中的数据，有数据变动时执行 this.watermark.changeOptions({ content: 'xxx' }) 可达到动态内容效果

**Comment by QW1kou** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/2a2ab67d-b738-47ae-a4ea-138029f3ef64)
这样吗？

**Comment by zhensherlock** [comment]
可以，也可以使用 this.watermark.changeOptions({ content: 'xxx' }, 'append') 只需传入需要更新的属性

**Comment by QW1kou** [comment]
好的，谢谢你，好人一生平安，官网的api可以补充一下

**Comment by zhensherlock** [comment]
水印删除也好了吗？

**Comment by QW1kou** [comment]
删除还是不行

**Comment by zhensherlock** [comment]
以下是我在codesandbox中Vue的示例
Vue2：https://codesandbox.io/s/prod-glade-v26dnt?file=/src/App.vue
Vue3：https://codesandbox.io/p/sandbox/wild-microservice-lsjrt3?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A26%2C38
对比看下，是不是中途哪里有改动过this.watermark的实例

**Comment by zhensherlock** [comment]
问下是要实现什么样的效果，同一处水印要添加多次？刚刚发现同一处水印添加多次，移除水印确实是有问题

**Comment by QW1kou** [comment]
想实现的是动态水印，刚才没找到changeOptions()这个方法就想把水印清除了重新添加 现在不用删除水印的方法了

**Comment by zhensherlock** [comment]
👌🏻
