### ISSUE TITLE
若容器为flex布局，水印会溢出容器

### ISSUE THREAD

**Issue by hongsir12** [zhensherlock/watermark-js-plus#156]
[codepen示例代码](https://codepen.io/HONGSIR-12/pen/wvRVxyr)
期望结果是水印只位于box3容器里边而不溢出

**Comment by zhensherlock** [comment]
水印用了absolute定位，需要在parent元素（示例中的box3）样式上添加`position: relative`

**Comment by hongsir12** [comment]
> 水印用了absolute定位，需要在parent元素（示例中的box3）样式上添加`position: relative`

示例已更改，若容器内部可滚动，则会导致水印展示不完整

**Comment by hongsir12** [comment]
看了下源码，建议增加配置项以设置水印元素宽高

**Comment by zhensherlock** [comment]
参考下这个 https://codepen.io/sunzhenxuan/pen/ZEVgVbg 需要改下布局结构

**Comment by zhensherlock** [comment]
也可以参考 https://zhensherlock.github.io/watermark-js-plus/guide/watermark.html#child-element-watermark 官方示例已改成可滚动的样式
