### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by QW1kou** [zhensherlock/watermark-js-plus#16]
用了水印导致页面一直在加载中

**Comment by QW1kou** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/14c5a954-34b2-4692-a294-eb800ce1c2ea)
这个元素一直在闪

**Comment by zhensherlock** [comment]
是不是有js一直尝试在删除水印节点，如果不需要侦听水印DOM，可添加 mutationObserve: false

**Comment by QW1kou** [comment]
好的，谢谢

**Comment by QW1kou** [comment]
添加完添加 mutationObserve: false，  changeOptions({})是不是就不起作用了

**Comment by QW1kou** [comment]
好的

**Comment by zhensherlock** [comment]
@QW1kou 已解决上述情况，请更新至最新版本v0.13.0
