### ISSUE TITLE
富文本水印在Firefox浏览器中不生效

### ISSUE THREAD

**Issue by zj9495** [zhensherlock/watermark-js-plus#17]
### 问题描述
<img width="1348" alt="image" src="https://github.com/zhensherlock/watermark-js-plus/assets/17064586/66e42b85-b703-420d-829c-a19ca508edac">

### 复现步骤
https://zhensherlock.github.io/watermark-js-plus/guide/watermark.html#rich-text-watermark

使用火狐浏览器打开文档页面，添加富文本水印
Firefox浏览器版本：116.0.2 (64 位)

### 环境详情

- **`watermark-js-plus` version:**
- **`vue` version:**
- **`react` version:**
- **`react-dom` version:**

**Comment by zj9495** [comment]
看起来是火狐下生成的水印图片是空白的
<img width="1246" alt="image" src="https://github.com/zhensherlock/watermark-js-plus/assets/17064586/984c73cd-2b62-4452-be59-ac040e3e4db4">

**Comment by zhensherlock** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/3541162/09ea1726-cc06-4461-b894-8c8978ba2a32)
目前排查下来的原因，是 `document.body.appendChild(bodyElement)` 在火狐执行后，不会马上显示，而是需要等待一定的时间后才会显示

**Comment by zj9495** [comment]
> ![image](https://user-images.githubusercontent.com/3541162/260917860-09ea1726-cc06-4461-b894-8c8978ba2a32.png) 目前排查下来的原因，是 `document.body.appendChild(bodyElement)` 在火狐执行后，不会马上显示，而是需要等待一定的时间后才会显示

看代码这里的`document.body.appendChild(bodyElement)`只是为了获取`offsetHeight` `offsetWidth`吗？火狐浏览器里调试已经正确返回了`offsetHeight` `offsetWidth`
<img width="1184" alt="image" src="https://github.com/zhensherlock/watermark-js-plus/assets/17064586/a4aa743f-92b0-4f22-a8f1-72be861c2e0a">

**Comment by zhensherlock** [comment]
是的，问题不在这里，好像是image load 回调事件没有执行
![image](https://github.com/zhensherlock/watermark-js-plus/assets/3541162/f0a356a1-1650-4f2a-9ba7-a52359a4e115)

**Comment by zhensherlock** [comment]
> > ![image](https://user-images.githubusercontent.com/3541162/260917860-09ea1726-cc06-4461-b894-8c8978ba2a32.png) 目前排查下来的原因，是 `document.body.appendChild(bodyElement)` 在火狐执行后，不会马上显示，而是需要等待一定的时间后才会显示
> 
> 看代码这里的`document.body.appendChild(bodyElement)`只是为了获取`offsetHeight` `offsetWidth`吗？火狐浏览器里调试已经正确返回了`offsetHeight` `offsetWidth` <img alt="image" width="1184" src="https://user-images.githubusercontent.com/17064586/260927350-a4aa743f-92b0-4f22-a8f1-72be861c2e0a.png">

已排查出问题，是svg标签没有设置width、height导致，稍等会进行修复。

**Comment by zhensherlock** [comment]
@zj9495 已解决上述情况，请更新至最新版本v1.1.0

**Comment by zj9495** [comment]
升级至v1.1.0版本后测试可以正常在Firefox显示富文本水印👍
