### ISSUE TITLE
react引入暗水印不生效

### ISSUE THREAD

**Issue by wyqjs** [zhensherlock/watermark-js-plus#2]

**Comment by zhensherlock** [comment]
观察下图中的dom是否添加成功。
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/3541162/209622372-7a0eb68b-481b-4840-9673-d1ca9c1475a6.png">
如果添加成功，确认下页面背景颜色是不是暗色的？
如果页面背景颜色是暗色的，可以在初始化时添加 `fontColor: '#fff'`
```js
const watermark = new BlindWatermark({
  content: 'hello my watermark',
  fontColor: '#fff',
  width: 200,
  height: 200
})
```

在解析暗水印时添加 `compositeOperation: 'overlay', fillColor: '#fff'`
```js
BlindWatermark.decode({
  compositeOperation: 'overlay',
  fillColor: '#fff',
  url: uploadFile.url,
  onSuccess: (imageBase64) => {
    decodeBlindImage.value = imageBase64
  }
});
```

**Comment by wyqjs** [comment]
![image](https://user-images.githubusercontent.com/95618257/209625084-a65d496c-c8aa-412b-9c7b-62ea481a63c2.png)![Snipaste_2022-12-27_14-57-59](https://user-images.githubusercontent.com/95618257/209625323-9ef903e8-a29b-4923-858f-95f11d999022.png)
添加上了但是没有效果
const watermark = new BlindWatermark({
                    content: `hello my watermark watermark`,
                    width: 200,
                    height: 200,
                    globalAlpha: 0.5,
                    onSuccess: () => {
                        // success callback
                        console.log('水印设置成功>>>>>>')
                    }
                })

**Comment by wyqjs** [comment]
> 观察下图中的dom是否添加成功。 <img alt="image" width="1371" src="https://user-images.githubusercontent.com/3541162/209622372-7a0eb68b-481b-4840-9673-d1ca9c1475a6.png"> 如果添加成功，确认下页面背景颜色是不是暗色的？ 如果页面背景颜色是暗色的，可以在初始化时添加 `fontColor: '#fff'`
> 
> ```js
> const watermark = new BlindWatermark({
>   content: 'hello my watermark',
>   fontColor: '#fff',
>   width: 200,
>   height: 200
> })
> ```
> 
> 在解析暗水印时添加 `compositeOperation: 'overlay', fillColor: '#fff'`
> 
> ```js
> BlindWatermark.decode({
>   compositeOperation: 'overlay',
>   fillColor: '#fff',
>   url: uploadFile.url,
>   onSuccess: (imageBase64) => {
>     decodeBlindImage.value = imageBase64
>   }
> });
> ```

https://github.com/zhensherlock/watermark-js-plus/issues/2#issuecomment-1365661764

**Comment by zhensherlock** [comment]
暗水印就是看不见的水印，如果要验证是否生效，可以先截图保存下来，然后在文档中 https://zhensherlock.github.io/watermark-js-plus/guide/blind-watermark.html#decode-blind-watermark
找到图中位置，上传图片，如果有解析出文字，说明暗水印添加成功了。
<img width="781" alt="image" src="https://user-images.githubusercontent.com/3541162/209746076-3af53aeb-e497-4525-ad1e-1f40c2c49ad7.png">

**Comment by wyqjs** [comment]
> 暗水印就是看不见的水印，如果要验证是否生效，可以先截图保存下来，然后在文档中 https://zhensherlock.github.io/watermark-js-plus/guide/blind-watermark.html#decode-blind-watermark 找到图中位置，上传图片，如果有解析出文字，说明暗水印添加成功了。 <img alt="image" width="781" src="https://user-images.githubusercontent.com/3541162/209746076-3af53aeb-e497-4525-ad1e-1f40c2c49ad7.png">
![下载](https://user-images.githubusercontent.com/95618257/209746444-357f4f77-a525-4ce6-99ec-cfde7fd6dbd3.png)解析出来是这样子,并没有文字

**Comment by zhensherlock** [comment]
这是我在codesandbox上的示例，你对比下代码
https://codesandbox.io/s/youthful-sid-ru1j15?file=/src/index.js

**Comment by wyqjs** [comment]
> 这是我在codesandbox上的示例，你对比下代码 https://codesandbox.io/s/youthful-sid-ru1j15?file=/src/index.js

![下载](https://user-images.githubusercontent.com/95618257/209748050-c3250986-be66-45b9-9f7c-102666e99809.png)
截图解析也并没有文字

**Comment by zhensherlock** [comment]
如果截图的内容不是暗色背景，不需要添加 `compositeOperation: 'overlay', fillColor: '#fff'`
直接使用下面的代码
```js
BlindWatermark.decode({
  url: uploadFile.url, // image url
  onSuccess: (imageBase64) => {
    // success callback
  }
});
```

**Comment by wyqjs** [comment]
> 如果截图的内容不是暗色背景，不需要添加 `compositeOperation: 'overlay', fillColor: '#fff'` 直接使用下面的代码
> 
> ```js
> BlindWatermark.decode({
>   url: uploadFile.url, // image url
>   onSuccess: (imageBase64) => {
>     // success callback
>   }
> });
> ```

![Snipaste_2022-12-28_10-50-58](https://user-images.githubusercontent.com/95618257/209749611-021e857b-5724-431f-b45c-9dd7b267be47.png)
是直接使用解析的

**Comment by zhensherlock** [comment]
将主题切换到淡色主题，再试下
我在深色主题下，自动添加了`compositeOperation: 'overlay', fillColor: '#fff'`

**Comment by wyqjs** [comment]
> 将主题切换到淡色主题，再试下 我在深色主题下，自动添加了`compositeOperation: 'overlay', fillColor: '#fff'`

ok了,感谢
