### ISSUE TITLE
盲水印图片decode是一张黑色背景图，看不到文字是什么原因啊

### ISSUE THREAD

**Issue by fanbinghuadev** [zhensherlock/watermark-js-plus#212]
盲水印图片decode是一张黑色背景图，看不到文字是什么原因啊
![image](https://github.com/zhensherlock/watermark-js-plus/assets/29560573/3f68e912-1881-44cb-b67a-e167a4033368)

**Comment by zhensherlock** [comment]
方便发一下原图吗

**Comment by fanbinghuadev** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/29560573/5f42a667-275d-4dbd-b68b-27577e9845b5)
就是用的这个示例生成的盲水印图片

**Comment by zhensherlock** [comment]
<img width="829" alt="image" src="https://github.com/zhensherlock/watermark-js-plus/assets/3541162/e3019c18-6ad9-4443-8e4a-3b4760c961e4">
这就奇怪了，我这边可以，你生成的盲水印图片发我看下，还有浏览器和操作系统都发下

**Comment by zhensherlock** [comment]
你可以截个全屏试试
