### ISSUE TITLE
请问，支持页面同时存在暗水印和明水印吗

### ISSUE THREAD

**Issue by Jess-2021** [zhensherlock/watermark-js-plus#225]
### Discussed in https://github.com/zhensherlock/watermark-js-plus/discussions/224

<div type='discussions-op-text'>

<sup>Originally posted by **Jess-2021** November 20, 2023</sup>
Hi, 请问是否有方法来实现同个页面上存在多种水印，有点类似多实例。

据我实践貌似不支持，看了源码貌似有个 `validateUnique` 方法来判断，我是否可以通过修改 `__WATERMARK__` 属性来达到目的效果？</div>

**Comment by zhensherlock** [comment]
是不是可以在body下放一个水印，然后在某个div下再放个水印（用parent属性）

**Comment by Jess-2021** [comment]
已解决。
