### ISSUE TITLE
加一行css就可以隐藏

### ISSUE THREAD

**Issue by simpleoo0o** [zhensherlock/watermark-js-plus#3]
header中添加<style>body > div:last-of-type {display: none!important;}</style>，即可隐藏水印

**Comment by zhensherlock** [comment]
该类问题与禁用JS后删除DOM节点一样，暂无没有很好的办法。

**Comment by zhensherlock** [comment]
@simpleoo0o 该问题已修复，请更新至最新版本v0.8.7
