### ISSUE TITLE
配置项parent不生效

### ISSUE THREAD

**Issue by taketo1015** [zhensherlock/watermark-js-plus#322]
### 问题描述

配置项：
parent
Type: Element | string
Default: 'body'
水印的容器。

设置后并没有生效，水印还是选中body

### 复现步骤
```html
<!doctype html>

<html>

<head>
    <title>test</title>
    <meta charset="UTF-8" />
</head>

<body style="font-family: IBM Plex Sans; font-weight: 200;background:#fff">
    <div id="a" style="width: 1000px; height: 1000px;"></div>
</body>

<script src="https://cdn.jsdelivr.net/npm/watermark-js-plus@1.3.32/dist/index.iife.min.js"></script>
<script>

    const watermark = new WatermarkPlus.Watermark(
        {
            content: 'hello my watermark',
            width: 200,
            height: 200,
            rotate: 22,
            layout: 'grid',
            parent: '#a',
            gridLayoutOptions: {
                rows: 2,
                cols: 2,
                gap: [20, 20],
                matrix: [[1, 0], [0, 1]]
            },
            advancedStyle: {
                type: 'linear',
                colorStops: [
                    {
                        offset: 0,
                        color: 'red'
                    },
                    {
                        offset: 1,
                        color: 'blue'
                    }
                ]
            }
        }
    )

    watermark.create()
</script>

</html>
```

### 环境详情

- **`watermark-js-plus` version:1.3.32**
- **html**

**Comment by zhensherlock** [comment]
<img width="1326" alt="image" src="https://github.com/zhensherlock/watermark-js-plus/assets/3541162/12023a12-2521-46ea-b313-c81778355553">
上面的代码，水印已经放到div#a中了，不清楚你说的是哪里没有生效

**Comment by taketo1015** [comment]
但是水印还是铺满了整个页面，可以设定在某一块区域内预览水印效果吗？感谢回复

> <img alt="图像" width="1326" src="https://private-user-images.githubusercontent.com/3541162/294890782-12023a12-2521-46ea-b313-c81778355553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTU5MzIsIm5iZiI6MTcwNDcxNTYzMiwicGF0aCI6Ii8zNTQxMTYyLzI5NDg5MDc4Mi0xMjAyM2ExMi0yNTIxLTQ2ZWEtYjMxMy1jODE3NzgzNTU1NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTIwNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM3ZGRhMjc0NmZlMTk0ZDM3NTBjZTRjNzMwZTI4YTVjMmRlM2NhMzcwOTA2MmZkMjY0OWU1OTllYWEyNWZhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ieANg16tMXERXmvJe7Pp4z_0vH8Uljp-lOSjQPlb_dE">上面的代码，水印已经放到div#a中了，不清楚你说的是哪里没有生效

**Comment by taketo1015** [comment]
> 在div#a 的style中添加 position: relative; 就可以了

非常感谢，成功了
