### ISSUE TITLE
能在 nodejs 中解水印吗

### ISSUE THREAD

**Issue by 18888628835** [zhensherlock/watermark-js-plus#35]
### 您建议的新功能或更新功能是什么？
希望能使用于 nodejs
### 为什么要包含此功能？
因为在前端加水印，在 nodejs 中解水印的需求还是挺普遍的

**Comment by zhensherlock** [comment]
欢迎使用 **@watermark-design/node** 类库
npm install @watermark-design/node

import * as watermark from '@watermark-design/node';

watermark.blind
  .decode({
    url: 'https://cdn.jsdelivr.net/gh/zhensherlock/oss@main/uPic/blind-watermark-test-bxEJgQ.png'
  })
  .then((res) => {
    console.log(res); // 解码后图片的base64
  });

**Comment by sheiy** [comment]
@zhensherlock 麻烦问下 node 生成水印背景怎么搞呢？

**Comment by zhensherlock** [comment]
> @zhensherlock 麻烦问下 node 生成水印背景怎么搞呢？

目前node端只支持解密水印，还不支持生成水印

**Comment by sheiy** [comment]
@zhensherlock 好的；多谢我把那个浏览器的canvs换成node-canvas 结果生成出来的图  有些情况下不能解析出水印。。尴尬

**Comment by sheiy** [comment]
用 你这个https://zhensherlock.github.io/watermark-js-plus/zh/ 上面那个demo的方式添加一个div不可以；但是给html的body添加background-image就行
