### ISSUE TITLE
浏览器缩放不是100%的时候水印内容不能完全显示

### ISSUE THREAD

**Issue by QW1kou** [zhensherlock/watermark-js-plus#38]
![20230830142017](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/1d87a50c-c017-424b-b901-681976758262)

**Comment by zhensherlock** [comment]
方便把代码贴下吗

**Comment by QW1kou** [comment]
setWatermark(){
			this.watermark = new Watermark({
				parent: '#screen_shot',
				contentType: 'rich-text',
				content: `<div style="color: rgba(255, 255, 255, 0.3)">${ this.$store.state.app.userInfo.full_name } ${ this.$store.state.app.userInfo.id } </div><div style="color: rgba(255, 255, 255, 0.3)">${ this.getDate() }</div>`,
				richTextWidth: 400,
				richTextHeight: 300,
				backgroundRepeat: 'repeat',
				backgroundPosition: '100% 100%',
				lineHeight: 300,
				fontColor: 'rab(255,255,248,1)',
				mutationObserve: true,
				unique: false,
				rotate: 40,
				mutationObserve: false,
				onSuccess: (val) => {}
			})
			
			this.watermark.create() // add watermark
		},

**Comment by QW1kou** [comment]
先把浏览器的缩放调整为非100%然后再使用水印

**Comment by zhensherlock** [comment]
方便在这个 https://codesandbox.io/s/brave-stitch-hfs2wk?file=/src/App.vue 上面复现下吗，我这边还是没有复现出来

**Comment by QW1kou** [comment]
在这上面复现不了

**Comment by zhensherlock** [comment]
你用的是哪个版本的？

**Comment by QW1kou** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/3fcf10d0-0db6-49ec-ad50-902b6fdd19ad)

**Comment by zhensherlock** [comment]
更新至1.2.1试试

**Comment by zhensherlock** [comment]
更新到1.2.1后还会有问题吗？

**Comment by QW1kou** [comment]
还是有问题

**Comment by QW1kou** [comment]
![image](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/e709f05a-4b20-4026-b9a8-3f2cc7b6418b)

**Comment by QW1kou** [comment]
正常的是这样
![image](https://github.com/zhensherlock/watermark-js-plus/assets/68577578/3cfc8e94-7d95-4440-b44f-4c8e98b3a0bf)

**Comment by zhensherlock** [comment]
水印内容显示不完全时，body标签上有什么样式吗？

**Comment by QW1kou** [comment]
没有

**Comment by zhensherlock** [comment]
我在官网和 codesandbox 上都无法重现这个情况，不好定位问题。有没有什么办法，能让我这边重现出来

**Comment by QW1kou** [comment]
要不建个项目？你在项目中试一下

**Comment by zhensherlock** [comment]
> 要不建个项目？你在项目中试一下

[test.zip](https://github.com/zhensherlock/watermark-js-plus/files/12517933/test.zip)
这个是我刚刚新建的项目，没有重新出来，你看下能不能重新。
