### ISSUE TITLE
支持图+文共存水印

### ISSUE THREAD

**Issue by tenglongwentian** [zhensherlock/watermark-js-plus#518]

**Comment by zhensherlock** [comment]
可以使用 Rich Text Watermark，content属性支持html内容
https://zhensherlock.github.io/watermark-js-plus/guide/watermark.html#rich-text-watermark

**Comment by tenglongwentian** [comment]
> 可以使用 Rich Text Watermark，content属性支持html内容 https://zhensherlock.github.io/watermark-js-plus/guide/watermark.html#rich-text-watermark

尝试了img标签，不行

**Comment by zhensherlock** [comment]
已解决上述情况，请更新至最新版本v1.4.17
