### ISSUE TITLE
利用css可隐藏水印

### ISSUE THREAD

**Issue by simpleoo0o** [zhensherlock/watermark-js-plus#6]
<style>body > div:last-of-type div {width: 0!important;height: 0!important;}</style>
![image](https://user-images.githubusercontent.com/23304206/225864924-b8a15599-f0c1-4ae4-bfe7-c31d47ebdf40.png)

**Comment by zhensherlock** [comment]
@simpleoo0o 感谢反馈，已解决上述情况，请更新至最新版本v0.8.10
