### ISSUE TITLE
关于盲水印，深色背景解析出来不展示水印问题

### ISSUE THREAD

**Issue by RelaxRick** [zhensherlock/watermark-js-plus#788]
### 问题描述

关于盲水印，深色背景解析出来不展示水印问题

### 复现步骤
具体
![浅色背景](https://github.com/user-attachments/assets/d4485e96-bb11-4274-9d45-b6a68595c877)
![深色背景](https://github.com/user-attachments/assets/5d037aaa-7311-44bf-8d99-9b34b9d8bcd4)

解析后如下
![解析](https://github.com/user-attachments/assets/b0f220a6-4b65-4903-aaa9-5532c9d5a80b)

浅色底可以正常展示

深色背景解析之后没有展示水印
![深色背景代码](https://github.com/user-attachments/assets/715c89b0-24da-4771-9a71-f8d668bbbaea)

**Comment by zhensherlock** [comment]
背景颜色的不同，解析的参数会有略微的改变，
根据上面上传的深色背景图片，修改 compositeTimes: 2 可以看到水印文字
调试参数网址：https://zhensherlock.github.io/watermark-js-plus/guide/custom/decode.html
<img width="687" alt="image" src="https://github.com/user-attachments/assets/84ad3c5c-73fd-4b35-a8db-c37a15b97b99">
结果：
![image](https://github.com/user-attachments/assets/c3bace3d-da45-4e45-b262-8d339360b6a5)

**Comment by RelaxRick** [comment]
感谢，目前深色背景解析出来了，但是我这边会有深色背景和浅色背景切换的情况出现，所以我同时添加两个水印，但是第二个水印会覆盖第一个水印，有方法可以解决吗？ 比如添加一个不同ID之类的，或者在不同的div上添加是不是可以解决这个问题
![image](https://github.com/user-attachments/assets/df13db72-c7ac-4cd2-9714-30ab84090fff)
