### ISSUE TITLE
 IE11下无法使用

### ISSUE THREAD

**Issue by zhanglingkun11** [zhensherlock/watermark-js-plus#809]
### 复现步骤
用ie11浏览器打开https://zhensherlock.github.io/watermark-js-plus/zh/guide/watermark.html，控制台语法错误，开发环境使用也无法显示水印
### 环境详情

- **`watermark-js-plus` version:**
- **`vue` version:**
- **`react` version:**
- **`react-dom` version:**

**Comment by zhensherlock** [comment]
官网是基于vitepress和vue3，vue3本身不支持ie11，暂时无法解决；watermark-js-plus 近期会发布支持ie11的版本，感谢反馈。

**Comment by zhensherlock** [comment]
你好，ie版本已发布，请参考文档：https://zhensherlock.github.io/watermark-js-plus/guide/extra/ie.html
