### ISSUE TITLE
在使用element-ui项目中使用出现调用失效情况

### ISSUE THREAD

**Issue by yezhihao17** [zhensherlock/watermark-js-plus#815]
### 问题描述

在使用了element-ui的项目中使用了MessageBox 弹框组件的 this.$prompt、this.$confirm等方法（需要触发两次以上）后，会生成两个水印dom，并且此时的dom监听事件失效（可以修改dom的css属性）。

### 复现步骤

demo地址：https://codepen.io/yezhihao17/pen/RwzjoqJ
点击demo的【点击打开 Message Box】按钮，然后点击弹窗的【取消】按钮，重复两次该操作。

### 环境详情

- **`watermark-js-plus` version: 1.5.2**

**Comment by zhensherlock** [comment]
我在chrome 127 上没有复现，方便提供浏览器信息吗？

**Comment by yezhihao17** [comment]
Google Chrome：版本 127.0.6533.100（正式版本） （64 位）
这是操作前后的效果
![企业微信截图_1723607947545](https://github.com/user-attachments/assets/0e2fde54-7303-4e1b-b15d-8dac19ab964a)
![企业微信截图_1723607976590](https://github.com/user-attachments/assets/402bf4a1-ba10-4a29-9e37-807f68455cd8)

图一是正常，图二是错乱，并且图二可以直接修改css的样式来隐藏

**Comment by zhensherlock** [comment]
已定位问题，感谢反馈，会近期更新

**Comment by zhensherlock** [comment]
已解决上述情况，请更新至最新版本v1.5.3

**Comment by yezhihao17** [comment]
感谢作者的快速响应，最新版本已解决上述问题。
