### ISSUE TITLE
偶发部分文字不透明度不生效

### ISSUE THREAD

**Issue by liuzhenkn** [zhensherlock/watermark-js-plus#848]
### 以前的Issues

无

### 问题描述
偶尔出现生成的图片上有一小部分不透明度不太对。
<img width="334" alt="image" src="https://github.com/user-attachments/assets/ca2eba95-be43-4ddd-b63d-faa8b4ebf70f">

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVAAAAFACAYAAADqPiRCAAAAAXNSR0IArs4c6QAAGx5JREFUeF7tnTmPLD35Rx/2fZVIIOFTsGRIBECCEBIBkJHwrfgCCCQgAhIyUhBLAkggJCKE9LLvcM9L/f6y6t89d/qZ6W67+5Q0ujPV5WrXse+R7cd2vaY8JCABCUigReA1rVQmkoAEJCCBUqBWAglIQAJNAgq0Cc5kEpCABBSodUACEpBAk4ACbYIzmQQkIAEFah2QgAQk0CSgQJvgTCYBCUhAgVoHJCABCTQJKNAmOJNJQAISUKDWAQlIQAJNAgq0Cc5kEpCABBSodUACEpBAk4ACbYIzmQQkIAEFah2QgAQk0CSgQJvgTCYBCUhAgVoHJCABCTQJKNAmOJNJQAISUKDWAQlIQAJNAgq0Cc5kEpCABBSodUACEpBAk4ACbYIzmQQkIAEFah2QgAQk0CSgQJvgTCYBCUhAgVoHJCABCTQJKNAmOJNJQAISUKDWAQlIQAJNAgq0Cc5kEpCABBSodUACEpBAk4ACbYIzmQQkIAEFah2QgAQk0CSgQJvgTCYBCUhAgVoHJCABCTQJKNAmOJNJQAISUKDWAQlIQAJNAgq0Cc5kEpCABBSodUACEpBAk4ACbYIzmQQkIAEFah2QgAQk0CSgQJvgTCYBCUhAgVoHJCABCTQJKNAmOJNJQAISUKDWAQlIQAJNAgq0Cc5kEpCABBSodUACEpBAk4ACbYIzmQQkIAEFah0YCby3qj5aVe+sql9W1ffFIwEJHCegQK0dI4EvV9WPq+q3m0h/V1XfFJEEJHCYgAK1ZoTAB160OD9RVV/ZTvD3Z6rqO1X1MzFJQAL/n4ACvc9a8dqqektVvb6qPlVV36iq91fVJzeB/mXD8vGqendVfe0+MfnUEniYgAK9zxryjqr6Z1X9rao+VlW/qqrfVNWXXnTdv11VP9+wMCb6+Z1U75OYTy2BAwQU6O1XC8r4P8Nj8jdBot9v55EkB+Odn95apV8frkeq362qX98+Kp9QAqcRUKCn8Vrx6ndV1R+r6l9b5um+0wLlHN34L27S/EVV/bCqPvuiVfq9qvpJVSHXz1XVVzfBrvj85lkCZyOgQM+Gdoobv66q3l5V/6iqPw85QqAcnP9rVSVg9K2qel9VfWSbxvSeqmI81DHQKYrTTMxGQIHOViL9/CBLjrQ0I0/+5vc/VNW/t2veXFVvGrrxnCbiTiv0R5tQP7i1UmmVekhAAgcIKND1qwVl+Naqomue8c4/beObnEOgtEL5N9H1dOP5++8bgi9U1U9fiPQH6yPxCSRwGQIK9DKcz/ktb9hak4xpciBLjvzN70xXetuuxfnGbQz0w1VFV526wHSmSPacefbeErgJAgp0vWLcd9XpjlOO+9YlY56MceZg3DNjnjnHvT60iZWgkYcEJHACAQV6AqwrX3qsq07rEokyLSkH0XWOsTVJS5XzjIWO05qu/Fh+vQTWJaBA1ym7Y111WpqZljQGkBgXRZbjQTeeqHuuW+fpzakEJiSgQCcslCNZeqirzngmZZlxzwSJMll+nac0pxJYiIACvX5hMQ5JObC0kmO/cig5RJLHuuosyaQVSkSd37kOiY6BpOs/qTmQwI0RUKDXLdBMPaK7zXglkuQYJ70nh+MKokNddUTMGCf/8jn3yLzP6z6l3y6BGyWgQK9XsAR/ECatRgRKYAeJpiU65oxr+Tzd+Ie66sdasNd7Ur9ZAjdKQIFetmBZ/YMIkSQtSoI6TC3ib2SKGDnPdZyjBZlWZeRqV/2yZea3SeAoAQV63sqBDMduNC1JoumcQ5DIMa1JxIhcKRPGMRErvyNW/s7UI7vq5y0z7y6BRxNQoI9GdfKFyJNVQcfmXfI5QkWmtDgjzrRGOT9OhN9nwK76yUViAgk8LwEF+vw8aVUmCMTYJkJEhPt16ZzL9CNamAR+ECnn+Ay57udxPm9uvZsEJPAkAgr0Sfj+L3Ei35yg1clkdcSZ1T+c5xwBI5hzngNR0jVHupxDpFzDOcZH+ftQUOl5cu1dJCCBJxFQoE/C92piGGYlEN3urBji96xbR5777ni68AhzL0vuScSd9M7lfHoZeQcJnIWAAu1hRX60EhPYQXYctBbphtP9pvWIOLNWfS9C7kEXn/NcQ7rMBc30Ju45BpB6uTWVBCRwFgIK9DSstAgRXbrbCJIjW8Mxjsm5tC4zFjp26/ONmcaUcU5asQkkpRt/Wu68WgISuCgBBfo43GkhIr1sxpEIO1LNCiIESosx3Xo2NuZzWqic5ycH1/Byt1e2E+O46ONy5VUSkMBVCSjQh/FnPJOrEhhCogiTHwQ5vqxtnLZESxVxZn36oWWVvPDNDT+u+l/AL5dAn4ACPcwOLsgQ6SUSnhVCGd9kvJPrxq3hMm0p0XY+jzgzKR6xMu7Jeedy9uuuKSVwdQIK9HgRZNySQBHSoyue9wch1f0YJnfimv0+nGOLlUg8ad3k4+pV3wxI4OkEFOhxhnmPUAJDmY9JsIeuOweSJXI+TlFiShKizcR4hgHSjXcn+KfXWe8ggWkIKNCHiwJZEklHggiUH8Y1Gf9M9z53iEQjXmQ5ToyfptDNiAQk8DwEFOjDHBFluu50zdP1zgR3/j7UlUe4D61jf57S8y4SkMBVCSjQh/FnOhKRclqeSDFdcz4jMp85oPu3YF61YP1yCUjg/AQU6P/WoWfDjxBPl51uOC1PxjDpmkeg2R0+29KRPvt8nr/U/AYJSGAKAvcq0HGfzuyAxIogxJld32lRZmu57KSUvTyz1BKxGlGfoiqbCQlcnsA9CjQ7JOU96ummI0x+5ye7JFEi2QSZaDtRdz5zqeXl66rfKIHpCNyLQDMXM5FxllBmezkKhVYnojy08xFp6eZn6tJ0hWiGJCCB6xC4dYEmQg7d7KBEy3PstqeVyfxNBDquLEqp7F/NcZ3S8lslIIGpCNy6QJEiY5R0v/OKjezNyRzPTIJHqPzQPeechwQkIIGXErglgTI3c9zRiJYkkhw3Myb4gygJGGX6Ud6QSRfdgNBLq4wXSEACIXArAs3qn2wll1cEM7aZpZjpxmd1Ud47BINMQ7JmSEACEng0gVsRaKLj2W8z71InWs7vtDjzug3mdSJVX5Xx6GrihRKQwCECKwo0e3SSd6YeIUOi6uOmHpnojjhphWZiPN180jA2SpfdF7b5/0ICEmgTmFGgD+2Rmeg5sszrNZAkrUymKI0BIDYrTsuTLv7YVc8L25ya1K46JpSABGYTaFYBRYS0JDkS3BnfXsm1eREbn/NZ1qMzBsrnmSy/L2nuu98M2dogAQlI4CQCswg0681pRea1GOl680ARIy1JZJmdkbK9HKJMVJ3r6daTxqj6SdXBiyUggVMIzCJQ5If0+KElmbXn2YsTYebdQXyOOAkYJfpORJ3pSr4m45TS91oJSOBJBC4t0IfGN7NdHNfsgzxjlJ1pSETXkWZarqRxffqTqoKJJSCBUwlcWqD7ie0Egmg10nUnEJTI+n5aUjYAIShEqxNxcjBWmvcUnfrsXi8BCUjgSQQuLdCsBCL6na46D4AYycv4rvXM38x7hJBvXpHxUEv2SUBMLAEJSOCxBC4t0GwdhxTzorVMemdiOy3LTEcahcnzjK3Vxz6f10lAAhI4G4FLCJSAUKLnBH+YesR45yvbU5EHJsLTKh2j8KTJksyzAfDGEpCABLoEzi3QcZcjxjHHlUPjSiBaoYiWc3TjES1RdQ8JSEAC0xI4t0BpWdI138/HHANGwMnSS66lFZqfacGZMQlIQALnFijjmJEhY5jj+nU+GzcwpsvOPNAEjSwdCUhAAlMTOLdAuT/jmEgROY7r17OayK761FXEzElAAscInFugfO/YsmRMlLFQWp5ORbJeSkACSxO4hECJuKcVSkvUNepLVxkzLwEJhMAlBMp30XXnOPTCNktDAhKQwJIELiXQJeGYaQlIQAIPEVCg1g8JSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJCABBWodkIAEJNAkoECb4EwmAQlIQIFaByQgAQk0CSjQJjiTSUACElCg1gEJSEACTQIKtAnOZBKQgAQUqHVAAhKQQJOAAm2CM5kEJHBxAu+tqo9W1Tur6pdV9f2L52D3hQr02iXg90tAAo8l8OWq+nFV/XYT6e+q6puPTXyO6xToOah6TwlI4LkJfOBFi/MTVfWV7cb8/Zmq+k5V/ey5v+yx91OgjyXldRKQwKUIvLaq3lJVr6+qT1XVN6rq/VX1yU2gf9ky8vGqendVfe1SGdt/jwK9Fnm/VwISOEbgHVX1z6r6W1V9rKp+VVW/qaovvei6f7uqfr4lZEz08zupXpSqAr0obr9MAhLYEcBB/xnO8TdBot9v55EkB+Odn95apV8frkeq362qX1+DrAK9BnW/UwISCIF3VdUfq+pf2wm677RAOUc3/oubNH9RVT+sqs++aJV+r6p+UlXI9XNV9dVNsBenqkAvjtwvlIAENgKvq6q3V9U/qurPAxUEysH5v1ZVAkbfqqr3VdVHtmlM76kqxkMdA7VKSUACN00AWXKkpRl58je//6Gq/r1d8+aqetPQjec0EXdaoT/ahPrBrZVKq/Rqhy3Qq6H3iyVwFwRwzFuriq55xjv/tI1vcg6B0grl30TX043n779vlL5QVT99IdIfzERNgc5UGuZFArdH4A1ba5IxTQ5kyZG/+Z3pSm/btTjfuI2Bfriq6KrjKqYzRbJTkFKgUxSDmZDAzRDYd9XpjuOZfeuSMU/GOHMw7pkxz5zjXh/axErQaLpDgU5XJGZIAksSONZVp3WJRJmWlIPoOsfYmqSlynnGQsdpTVPDUKBTF4+Zk8AyBI511WlpZlrSGEBiXBRZjgfdeKLuuW76h1eg0xeRGZTAEgQe6qoznolrMu6ZIFEmyy/xgIcyqUCXLTozLoGLEGAcEk+wtJJjv3IomUCSx7rqLMmkFUpEnd+5DomOgaSLPMxzf4kCfW6i3k8Ct0MgU4/objNeiSQ5xknvedpxBdGhrjoiZoyTf/mce2Te57LEFOiyRWfGJXBWAgR/ECatRgRKYAeJpiU6fjnX8nm68Q911Y+1YM/6MOe6uQI9F1nvK4H1CLD6BxEiSVqUBHWYWsTfyBQxcp7rOEcLMq3KyPUmu+rHilKBrlfJzbEEnosAMhy70bQkiaZzDkEix7QmESNyxRmMYyJWfkes/J2pRzfZVVegz1XlvI8EboMA8mRV0LF5l3yOUJEpLc6IM61Rzo8T4fdUbqqrrkBvo9L7FBJ4CgGkRqsyQSDGNhEiItyvS+dcph/RwiTwg0g5x2fIdT+P8yl5WzKtXfgli81MS+AkAol8k4hWJ5PVEWdW/3CecwSMcALnORAlXXOkyzlEyjWcY3yUvw8FlU7K3MoXK9CVS8+8S+DlBPg/npVAdLuzYojfs24dee674+nCI8y9LLknEXfSLz+X8+UIj1+hQJ9Cz7QSmJMA8qOVmMAOsuOgtUg3nO43rUfEmbXqexFyD7r4nOca0mUuaKY3cc8xgDQnjTPmSoGeEa63lsCFCdAiRHTpbiNIjmwNxzgm59K6zFjo2K1PljONKeOctGITSEo3/sKPN9/XKdD5ysQcSeBUAmkhIr1sxpEIO1LNCiIESosx3Xo2NuZzWqic5ycH1/Byt1e2E+O46Kn5u9nrFejNFq0PdgcEMp7JoyYwhEQRJj8IcnxZ2zhtiZYq4sz69EPLKnnh2/IbfpyzHijQc9L13hI4DwH+3yJDpJdIeFYIZXyT8U6uG7eGy7SlRNv5POLMpHjEyrgn5+9iLudTikiBPoWeaSVwPQIZtyRQhPToiuf9QUh1P4ZJTrlmvw/n2GIlEk/a5Tf5uFSxKNBLkfZ7JPC8BPIeoQSGMh+TYA9ddw4kS+R8nKLElCREm4nxDAOkG7/MTvDPi7J/NwXaZ2dKCVybALIkko4EESg/jGsy/pnuffIYiUa8yHKcGH/tZ1ny+xXoksVmpiXwKgFEma47XfN0vTPBnb8PdeUR7kPr2MX7SAIK9JGgvEwCExLIdCQi5bQ8kWK65nxGZD5zQPdvwZzwcdbLkgJdr8zM8X0RYB16NvzIk6fLTjeclidjmHTNI9DsDp9t6UiffT7vi96Zn1aBnhmwt5dAg8C4T2d2QGJFEOLMru+0KLO1XHZSyl6eWWqJWI2oNwrgsUkU6GNJeZ0ELkMgOyTlPerppiNMfucnuySRo2yCTLSdqDufudTyMmX1amF4SEAC1yWQuZiJjLOEMtvLkTNanYjy0M5HpKWbn6lL132SO/t2BXpnBe7jTkUgEXIylR2UaHmO3fa0Mpm/iUDHlUV5mP2rOaZ6yFvOjAK95dL12WYngBQZo6T7nVdsZG9O5nhmEjxC5YfuOec8JiGgQCcpCLNx8wSYmznuaERLEkmOmxkT/EGUBIwy/ShvyKSLbkBosmqiQCcrELNzkwSy+idbyeUVwYxtZilmuvFZXZT3DvF/NNOQbhLOyg+lQFcuPfO+CoFEx7PfZt6lTrSc32lx5nUbzOtEqnf9qoxVClaBrlJS5nMVAtmjk/9bTD1ChkTVx009MtEdcdIKzcR4uvmkYWyULvtdv7BthQJXoCuUknmcicBDe2Qmeo4s83oNJEkrkylKYwCIzYrT8qSLP3bV88I2pybNVPIH8qJAJy8gszcVgawCighpSXIkuDO+vZJr8yI2PuezrEdnDJTPM1l+/5Dcd78Z8lQgzMz/CChQa4IEXk4g681pRea1GOl6kzpipCWJLLMzUraXQ5SJqnM93XrSGFV/Ofupr1CgUxePmZuEAPJDevzQksza8+zFiTDz7iA+R5wEjBJ9J6LOdCVfkzFJgT5XNhToc5H0PrdA4KHxzWwXxzX7IM8YZWcaEtF1pJmWK2lcn34LNWT3DAr0BgvVR2oT2E9sJxBEq5GuO4GgRNb305KyAQhBIVqdiJODsdK8p6idKRPOS0CBzls25uzyBLISiOh3uurkAjHyf2V813rmb+Y9Qsg3r8h4qCV7+afyG89GQIGeDa03XpBAto5DinnRWia9M7GdlmWmI43C5FHH1uqCj26WOwQUaIeaaW6JAAGhRM8J/jD1iPHOV7aH5P8IE+FplY5ReNJkSeYt8fBZTiCgQE+A5aU3R2Dc5YhxzHHl0LgSiFYoouUc3XhES1Td484JKNA7rwB3/vi0LOma7+djjgEjEGXpJdfSCs3PnePz8RWodeCeCTCOGRkyhjmuX+ezcQNjuuzMA03Q6J65+ezD+I4wJHCvBBAm45hIETmO69ezmsiu+r3Wjkc8ty3QR0DykpsmMLYsGRNlLJSWp1ORbrrYn+fhFOjzcPQu6xIg4p5WKC1R16ivW5YXz7kCvThyv3BCAnTdOQ69sG3C7JqlWQgo0FlKwnxIQALLEVCgyxWZGZaABGYhoEBnKQnzIQEJLEdAgS5XZGZYAhKYhYACnaUkzIcEJLAcAQW6XJGZYQlIYBYCCnSWkjAfEpDAcgQU6HJFZoYlIIFZCCjQWUrCfEhAAssRUKDLFZkZloAEZiGgQGcpCfMhAQksR0CBLldkZlgCEpiFgAKdpSTMhwQksBwBBbpckZlhCUhgFgIKdJaSMB8SkMByBBTockVmhiUggVkIKNBZSsJ8SEACyxFQoMsVmRmWgARmIaBAZykJ8yEBCSxHQIEuV2RmWAISmIWAAp2lJMyHBCSwHAEFulyRmWEJSGAWAgp0lpIwHxKQwHIEFOhyRWaGJSCBWQgo0FlKwnxIQALLEVCgyxWZGZaABGYhoEBnKQnzIQEJLEdAgS5XZGZYAhKYhYACnaUkzIcEJLAcAQW6XJGZYQlIYBYCCnSWkjAfEpDAcgQU6HJFZoYlIIFZCCjQWUrCfEhAAssRUKDLFZkZloAEZiGgQGcpCfMhAQksR0CBLldkZlgCEpiFgAKdpSTMhwQksBwBBbpckZlhCUhgFgIKdJaSMB8SkMByBBTockVmhiUggVkIKNBZSsJ8SEACyxFQoMsVmRmWgARmIaBAZykJ8yEBCSxHQIEuV2RmWAISmIWAAp2lJMyHBCSwHAEFulyRmWEJSGAWAgp0lpIwHxKQwHIEFOhyRWaGJSCBWQgo0FlKwnxIQALLEVCgyxWZGZaABGYhoEBnKQnzIQEJLEdAgS5XZGZYAhKYhYACnaUkzIcEJLAcAQW6XJGZYQlIYBYC/wV8x9Nuo7JKIAAAAABJRU5ErkJggg==

### 复现步骤

配置信息：
            contentType: 'text',
            content: 'default watermark',
            width: 200,
            height: 190,
            rotate: 25,
            fontWeight: 'normal',
            fontSize: '15px',
            globalAlpha: 0.06,
            layout: 'grid',
            fontFamily: 'sans-serif',
            gridLayoutOptions: {
                rows: 2,
                cols: 2,
                gap: [10, 10],
                matrix: [
                    [1, 0],
                    [0, 1]
                ],
            },
### 环境详情

- **`watermark-js-plus` version:1.5.2**

**Comment by zhensherlock** [comment]
能提供下其他的信息吗?比如浏览器版本
最好在 https://stackblitz.com/edit/vue2-vite-starter-t8cew5 上可以复现，便于快速定位问题

**Comment by liuzhenkn** [comment]
> filter和advancedStyle 参数有用到吗？

没呢 只用到了如下参数。
![image](https://github.com/user-attachments/assets/f9ef09e9-dde6-400b-8999-b6989e3afe75)

**Comment by zhensherlock** [comment]
尝试以下代码，看看能不能规避问题：
globalAlpha: 1,
filter: 'opacity(6%)',

**Comment by liuzhenkn** [comment]
> 尝试以下代码，看看能不能规避问题： globalAlpha: 1, filter: 'opacity(6%)',

好的感谢，我们先修改一下试试，毕竟是偶现的所以不能立刻看到效果，如果还有问题我们再来反馈。

**Comment by liuzhenkn** [comment]
打扰了 filter: 'opacity(6%)' 在 Safari 上不生效，可能还是要看下这个问题。

**Comment by zhensherlock** [comment]
[https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/filter](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/filter)
<img width="847" alt="image" src="https://github.com/user-attachments/assets/ee3b29f0-4010-4b45-9b33-bdd87000f9f4">
Safari不支持filter，能不能在safari下还是用globalAlpha: 0.06

```javascript
{
  ...(isSafari ? {
    globalAlpha: 0.06,
  } : {
    globalAlpha: 1,
    filter: 'opacity(6%)',
  })
}
```

**Comment by CrazyJET** [comment]
我可以复现这问题，浏览器缩放到75%或以下，刷新页面就会出现这个问题！麻烦修复一下，谢谢 @zhensherlock

**Comment by liuzhenkn** [comment]
hello 能交流一下嘛 我这里不能稳定复现  wx: l314339793 @CrazyJET

**Comment by liuzhenkn** [comment]
我这里确实之前出现问题的设备也复现了，但是有的设备不能复现，
复现路径使用 command + - 缩放，然后刷新页面，就会稳定复现类似问题，而且这个后面的颜色还深浅不定，用户反馈有时候颜色很深。

复现浏览器版本及设备：
<img width="529" alt="image" src="https://github.com/user-attachments/assets/4ab3b1f1-053f-4518-b1da-09597741bcd1">
![企业微信截图_618fab9a-f69a-48c5-82ef-ea290fcfbf46](https://github.com/user-attachments/assets/7031ba36-f6d4-4425-b03a-b98ed1d84909)

@zhensherlock

**Comment by zhensherlock** [comment]
@liuzhenkn
https://stackblitz.com/edit/vue2-vite-starter-t8cew5?file=src%2FApp.vue
这个链接，你那边缩放后可以复现吗？

**Comment by CrazyJET** [comment]
![image](https://github.com/user-attachments/assets/88d1fe19-3891-4726-9ee0-6204ea8754f0)
可以用一个demo文件（直接打开demo文件，不要用项目开发环境），测试一下

**Comment by liuzhenkn** [comment]
@zhensherlock 那个链接不太好操作 我使用 @CrazyJET 的 html 在有问题的电脑上可以复现。感觉 M2 没这个问题，M1 和 windows 有些会触发。

<img width="1436" alt="企业微信截图_dae70cbf-d565-4e50-9cd2-7e5a14143aae" src="https://github.com/user-attachments/assets/38173d7c-f640-445f-beb8-fdf5f6be467f">
<img width="721" alt="企业微信截图_43787871-38ee-48be-9c0b-645f139df051" src="https://github.com/user-attachments/assets/89442ad8-55b4-4772-99b6-e5f05f42bc4e">
<img width="586" alt="企业微信截图_ac1a147b-17e0-4df1-8e60-0bb7abf7f7fe" src="https://github.com/user-attachments/assets/d37a4584-1c3c-4fd1-a5ec-59199bb8c650">

**Comment by zhensherlock** [comment]
发现问题了，感谢 @liuzhenkn @CrazyJET ，今天晚些时间发布一个版本

**Comment by zhensherlock** [comment]
已解决上述问题，请更新至最新版本v1.5.6。

**Comment by liuzhenkn** [comment]
> 已解决上述问题，请更新至最新版本v1.5.6。

收到 感谢 我们线上验证一下。

**Comment by liuzhenkn** [comment]
我这边验证没问题了，我先 close 了。
