### ISSUE TITLE
check 无法检测水印是否存在

### ISSUE THREAD

**Issue by hooray** [zhensherlock/watermark-js-plus#858]
https://github.com/zhensherlock/watermark-js-plus/blob/b202910c105c48814d9db32e2290ec824daa36e1/src/core/watermark.ts#L114-L119

看代码应该是实现了一次重载？不能检测是否存在

**Comment by zhensherlock** [comment]
这个方法名和实现的代码确实不匹配，是不是只要改成 判断一下水印元素是否存在就可以了？

**Comment by hooray** [comment]
嗯，我理解 check 方法应该只要返回一个 boolean 值就行。

不太清楚原有这段代码是否有其他用途，如果有的话，可以改个方法名。

**Comment by zhensherlock** [comment]
v1.5.5中已修改check方法体，感觉反馈。
