### ISSUE TITLE
MutationObserver 和 requestAnimationFrame 不可写，导致部分库不可用

### ISSUE THREAD

**Issue by liuzhenkn** [zhensherlock/watermark-js-plus#863]
### 问题描述

bootstrap 中设置了 MutationObserver 和 requestAnimationFrame 不可写，导致部分库不可用

![image](https://github.com/user-attachments/assets/1c15aa53-1ca0-4a73-b16b-da854fd1c8a4)
![image](https://github.com/user-attachments/assets/844061a6-8858-4b12-998f-e82fa57c0593)

能否可以选择设置，或者解决类似问题？

### 复现步骤

举了个比较简单的例子，就是如果我水印初始化的比较早，然后antv_g2 引用的晚的情况。实际项目是，router 切换时才加载 antv_g2。
https://stackblitz.com/edit/vitejs-vite-9tf5bt?file=package.json,src%2FApp.vue&terminal=dev

可以看下控制台报错

### 环境详情

- **`watermark-js-plus` version:*1.5.3*

**Comment by liuzhenkn** [comment]
能否添加参数可以不限制那么严格或者有其他解决方案呢？

**Comment by liuzhenkn** [comment]
> 下个版本，加个参数用来绕过设置MutationObserver和 requestAnimationFrame只读的代码

好的感谢，下个版本计划什么时候上呢。

**Comment by zhensherlock** [comment]
尽量今天晚上发布

**Comment by zhensherlock** [comment]
已解决上述问题，请更新至最新版本v1.5.5即可。已添加新参数`monitorProtection`，默认绕过设置`requestAnimationFrame`

**Comment by liuzhenkn** [comment]
好的 感谢
