### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by wjp980108** [zhensherlock/watermark-js-plus#917]
### 以前的Issues
#583 

### 问题描述
项目中使用最新版 watermark-js-plus 提示以下错误
Uncaught SyntaxError: Unexpected token 'export' (at app.bundle.js?rev=hash:126586:2)
![image](https://github.com/user-attachments/assets/e8886192-db50-47d6-af6f-ce5042418066)

### 复现步骤
<script>
	import { Watermark} from "watermark-js-plus";
</script>

### 环境详情

- **`watermark-js-plus` version:1.5.6
- **`vue` version:1.0.26
- **`node` version:8.17.0

**Comment by zhensherlock** [comment]
vue版本是1.0.26？

**Comment by wjp980108** [comment]
> vue版本是1.0.26？方便在stackblitz上复现吗？

感谢大佬的回复，版本是 1.0.26 ，公司的老项目了，刚领导说不需要加水印了😂
