### ISSUE TITLE
ie版本的仓库没了 watermark-js-plus/ie

### ISSUE THREAD

**Issue by LJNaN** [zhensherlock/watermark-js-plus#934]
## ie版本的仓库没了 watermark-js-plus/ie

**Comment by zhensherlock** [comment]
一直在啊，https://stackblitz.com/edit/webpack-webpack-js-org-dysy1x?file=src%2Findex.js

**Comment by LJNaN** [comment]
> 一直在啊，https://stackblitz.com/edit/webpack-webpack-js-org-dysy1x?file=src%2Findex.js

不好意思我以为是另一个仓库😂，感谢
