### ISSUE TITLE
IE11无法兼容

### ISSUE THREAD

**Issue by LJNaN** [zhensherlock/watermark-js-plus#935]
### 问题描述
IE11环境无法使用，有报错
IE不支持 canvas ctx 的 resetTransform 方法，引发报错，阻塞进程
![image](https://github.com/user-attachments/assets/e571b658-5067-4b36-8b76-3cf05010575b)
![image](https://github.com/user-attachments/assets/a4460032-f399-462a-8585-caaec5fd5204)

### 关键代码
![image](https://github.com/user-attachments/assets/ac980cda-0731-408d-b6f7-3fee9f4a0649)

其实在我的使用过程，使用简单的文本水印，不使用 resetTransform 等方法，在IE也能正常渲染
![image](https://github.com/user-attachments/assets/4f4459c1-a508-4b60-8b49-58b4dcdb7218)

**Comment by zhensherlock** [comment]
确实是个问题，感谢反馈，我加一个resetTransform polyfill，近期更新一版

**Comment by zhensherlock** [comment]
感谢反馈，已解决上述问题，请更新至最新版本v1.5.7即可
