### ISSUE TITLE
水印宽高、行列间距优化

### ISSUE THREAD

**Issue by liesauer** [zhensherlock/watermark-js-plus#936]
如图，目前以宽高的方式控制间距，当以一定角度显示时，受高度的限制，内容会被截断，如果将高度调大，虽然能显示完，但是行距就变得很大，没办法保持小间距的情况下显示完整。官网可复现，水印高度直接改24。

![image](https://github.com/user-attachments/assets/a8bffd3f-542f-4235-90cc-bd34f061d467)

![image](https://github.com/user-attachments/assets/e8c12515-e7b9-4a4c-ac18-cf8428d672a5)

![image](https://github.com/user-attachments/assets/bc86e587-1301-4686-bd38-2960b886ca2a)

**Comment by zhensherlock** [comment]
目前逻辑是这样的，你这边想要实现什么样的效果？

**Comment by liesauer** [comment]
> 目前逻辑是这样的，你这边想要实现什么样的效果？

保持小间距的同时能够完整显示文字内容
![image](https://github.com/user-attachments/assets/6a198ba0-ac0c-4100-9b65-617e2254d003)

**Comment by zhensherlock** [comment]
生成水印图片的时候，会把溢出的内容截掉，建议使用富文本水印进行代替，以下是示例：
https://stackblitz.com/edit/vue2-vite-starter-72e8py?file=src%2FApp.vue

**Comment by liesauer** [comment]
> 生成水印图片的时候，会把溢出的内容截掉，建议使用富文本水印进行代替，以下是示例： https://stackblitz.com/edit/vue2-vite-starter-72e8py?file=src%2FApp.vue

还有个问题，目前是先把dom添加在body上，再截图贴到target上？我们的程序目前会有一个比较重的图片合成模块，所以就导致了，添加水印时，会需要比较多的时间才能所有东西做完，大概3-5秒，网页上就会显示一堆的水印div，这个怎么处理？
![image](https://github.com/user-attachments/assets/cedc1387-3655-4240-a562-2518b40a95d4)

**Comment by zhensherlock** [comment]
是的，因为要先验证富文本的html是否正确，然后再执行html to canvas的逻辑，可以对body进行高度限制吗，溢出的部分hidden。

**Comment by liesauer** [comment]
> 是的，因为要先验证富文本的html是否正确，然后再执行html to canvas的逻辑，可以对body进行高度限制吗，溢出的部分hidden。

嗯，目前先这么处理了。
